version: '3'
services:
  wumpus-and-the-octocat:
    build:
      dockerfile: Dockerfile
      context: ./
    volumes:
      - "./certs:/etc/ssl/"
    environment:
      APP_HOSTNAME: "host.docker.internal"
      APP_PORT: "8080"
      APP_HTTP2_ENABLED: ""
      APP_HTTP2_KEY: "/etc/ssl/localhost-privkey.pem"
      APP_HTTP2_CERT: "/etc/ssl/localhost-cert.pem"
    env_file:
      - "config/docker-config.env"
    ports:
      - "8080:8080"
